version: "3"
services:
  db:
    container_name: donjjul-db
    image: mysql
    environment:
      MYSQL_DATABASE: donjjul
      MYSQL_ROOT_PASSWORD: donjjul
      TZ: Asia/Seoul
#    volumes:
#      - ./db/data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci