spring:
  sql:
    init:
#      data-locations: classpath:sql/schema.sql
#      mode: always

  datasource:
    url: jdbc:mysql://localhost:3306/donjjul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: donjjul

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
  profiles:
    include: auth, jwt